language: lua

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
    - os: linux
      dist: trusty
      sudo: required

install:
  - ./.travis/install.${TRAVIS_OS_NAME}.sh

script:
  - ./.travis/run.${TRAVIS_OS_NAME}.sh
